### ISSUE TITLE
Engine selection from URL sometimes (?) causes invalid API request

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#12]
E.g. https://test262.fyi/#built-ins/undefined|libjs, when navigated to directly.

Oddly it seems to work sometimes, but not all of the time...

![image](https://github.com/CanadaHonk/test262.fyi/assets/19366641/397530cc-d49a-40b1-a1fb-71cb93fba850)

**Comment by CanadaHonk** [comment]
Fixed this in main already, run soon ;)
