### ISSUE TITLE
Nashorn and Rhino missing from results

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#22]
Curiously nashorn does not appear in the URL when selecting all engines:

```
https://test262.fyi/#|v8,v8_exp,sm,sm_exp,jsc,hermes,qjs,libjs,libjs_bc,chakra,graaljs,xs,rhino,boa,engine262,babel
```

rhino does but is not visible as a checkable entry. Neither seem to be included in the results anywhere

**Comment by linusg** [comment]
Both are not included in https://test262.fyi/data/engines.json, which is probably the reason for this.

**Comment by CanadaHonk** [comment]
The issue is they are taking too long in the CI so are being killed before completing or causing Node to crash from memory overflow :P

**Comment by CanadaHonk** [comment]
This has been fixed in last few days/commits, seems stable now. Will reopen if not so.

**Comment by MendyBerger** [comment]
This issue seems to persist but with other engines. Hermes and Porffor both don't show up.

`https://test262.fyi/#|v8,hermes,porffor`
