### ISSUE TITLE
ES2023 and ES2024 missing

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#46]
This is no longer accurate:

https://github.com/CanadaHonk/test262.fyi/blob/78cb8ddcf97cb42c3c40117d35bc6d484caf0437/site/index.html#L337-L338

https://github.com/CanadaHonk/test262.fyi/blob/78cb8ddcf97cb42c3c40117d35bc6d484caf0437/site/generate.mjs#L241

ESNext is now ES2025, i.e. edition 16: https://github.com/tc39/ecma262/commit/d502ea4acdde7e89a7e042dcc4e9123c6c75f476

**Comment by nektro** [comment]
es2024 is now officially released
