### ISSUE TITLE
Mode to sort leaderboard by percentage and time

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#47]
Doesn't need to be the default but would be nice as an option IMO :)

| I.e. turning this... | ...into this |
| - | - |
| <img src="https://github.com/CanadaHonk/test262.fyi/assets/19366641/e325583d-400c-40ce-84fc-8747eac2edee" height="800" alt="image"> | <img src="https://github.com/CanadaHonk/test262.fyi/assets/19366641/7242a61e-f825-4c6d-b1dd-4cc20e58e66d" height="800" alt="image"> |

**Comment by CanadaHonk** [comment]
Probably done in 91292be0546c43ad9429308ff9e6c1a4335943ba

**Comment by linusg** [comment]
Works great, ty :)
Do we want to do anything with the time bars as well or leave them as is?

**Comment by CanadaHonk** [comment]
The sort function for time was erroring, oops. Should be fixed in f3ed02b839a6815913c6d41d7518ebfe94847561

**Comment by linusg** [comment]
🎉

![image](https://github.com/CanadaHonk/test262.fyi/assets/19366641/61020f36-740a-4276-849d-fd43b13d4855)

**Comment by CanadaHonk** [comment]
Do we want all graphs to be sorted like this or just the overall ones? Eg:
1. Feature and edition graphs
2. File/folder graphs

**Comment by linusg** [comment]
looks like it automatically applied to all of them, which seems fine to me.
