### ISSUE TITLE
Clickable directory/file labels should be links

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#5]
Using `<th>`+`onclick` is not keyboard-accessible, nor does it allow me to open multiple ones in a new tab but forces awkward back and forth navigation.

(these:)

![image](https://github.com/CanadaHonk/test262.fyi/assets/19366641/6ff20cc0-79e1-40d7-ac57-46f4f3b061b6)

**Comment by CanadaHonk** [comment]
Done in last commit :)
