### ISSUE TITLE
Use different method for testing SWC

### ISSUE THREAD

**Issue by kdy1** [CanadaHonk/test262.fyi#54]
The current method cannot test SWC correctly.

**Comment by CanadaHonk** [comment]
Hi, thanks for creating the issue. The plugin isn't used anymore and is mostly dead code I believe. I'll just remove it, but feel free to make a PR re-adding it as a Rust plugin if it benefits SWC's results. Thank you!

**Comment by styfle** [comment]
Something is definitely wrong with the results. There's no way SWC would only pass 48% of ES6 tests.

<img width="574" alt="image" src="https://github.com/CanadaHonk/test262.fyi/assets/229881/7411b980-198d-4bcc-9378-109dfcc68892">

Could be related to ES5 being used here:

https://github.com/CanadaHonk/test262.fyi/blob/201eaf7fb47150e803c10dbce880e6f36ba855b8/helpers/swc/transpile.js#L10

**Comment by kdy1** [comment]
I updated the title. I think you should use something like `babel-test262-runner` instead.

**Comment by CanadaHonk** [comment]
Should be fixed now?

**Comment by styfle** [comment]
@CanadaHonk I'm not seeing swc on the https://test262.fyi website anymore 🤔
