### ISSUE TITLE
Many results missing

### ISSUE THREAD

**Issue by nicolo-ribaudo** [CanadaHonk/test262.fyi#56]
<img width="325" alt="image" src="https://github.com/CanadaHonk/test262.fyi/assets/7000710/00432ec6-a289-4563-8bf0-c12be4e10ffc">

I'm not sure what's going on, but it seems like most CI is red. Maybe try restarting it? :)

**Comment by CanadaHonk** [comment]
Uh oh. Restarted :crossed_fingers:

**Comment by CanadaHonk** [comment]
Found the bug :tada: (one engine was newly crashing during esvu install and we do not handle that atm), will fix and rerun now

**Comment by michaelficarra** [comment]
@CanadaHonk This seems to be happening again.

<img width="565" alt="image" src="https://github.com/CanadaHonk/test262.fyi/assets/218840/e1ccbb8a-2413-4973-b6ea-e26ae618fb52">

**Comment by CanadaHonk** [comment]
It's running right now (runs daily at midnight UTC) so shows partial results it currently has

**Comment by michaelficarra** [comment]
Okay, thanks. I'll open a feature request for in-progress results to incrementally update instead of clearing out existing data.
