### ISSUE TITLE
Long proposal name causes horizontal scroll

### ISSUE THREAD

**Issue by linusg** [CanadaHonk/test262.fyi#7]
(scrollbar not visible because modern UI)

![image](https://github.com/CanadaHonk/test262.fyi/assets/19366641/cd55366a-4ab9-4063-b582-bc38046848e9)

**Comment by CanadaHonk** [comment]
Note that I trimmed the names in UI further (removing excess `... Proposal` and somewhat unneeded/verbose `... .prototype. ...`) which should help for now, but still remains an issue.

**Comment by CanadaHonk** [comment]
This is mostly not an issue for now and unlikely to come up again - we should trim proposal names so they should never be this long ever really, if not they should probably be trimmed further.
